name: Rails CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        USER_NAME: ${{ secrets.USER_NAME }}
        HOST_NAME: ${{ secrets.HOST_NAME }}
        ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
        ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
        MAIL_ADDRESS: ${{ secrets.MAIL_ADDRESS }}
        MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOST_NAME} << EOF
          bash -lc "
            export NVM_DIR=\$HOME/.nvm
            source \$NVM_DIR/nvm.sh
            cd mygolfnote 
            git pull origin main 
            ~/.rbenv/shims/bundle install --without development test
            ~/.rbenv/shims/bundle exec rails assets:precompile RAILS_ENV=production 
            ~/.rbenv/shims/bundle exec rails db:migrate RAILS_ENV=production 
            if [[ -e tmp/pids/puma.pid ]]; then 
              sudo kill $(cat tmp/pids/puma.pid)
            fi 
            ~/.rbenv/shims/rails s -e production
          "
        EOF